[binance]
api_key = "qq0lZOBeIaFwadnZOYlORzXyBbYQnUOM6AZml3EyMeOqLRRQHF0E8SZKXQJ6uKXo"
api_secret = "5vUoQDH920MOgjW0EWz9T6rcqzXwlrTWwMH13x68a4lYhEqYjSe0Iu4M11EMKTZ1"

[secrets]
ALPHA_VANTAGE_API_KEY = "7UHCDIE0JBLVOQMC"
BINANCE_API_KEY = "qq0lZOBeIaFwadnZOYlORzXyBbYQnUOM6AZml3EyMeOqLRRQHF0E8SZKXQJ6uKXo"
BINANCE_API_SECRET = "your_secret_5vUoQDH920MOgjW0EWz9T6rcqzXwlrTWwMH13x68a4lYhEqYjSe0Iu4M11EMKTZ1here"